### ISSUE TITLE
User not entirely sure if they can leave fields blank or not

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#101]
This came up when entering information in the “Demographics” section. This seemed like a common takeaway in general, though.

**Comment by bengolder** [comment]
I think we should mark questions that are required for eligibility.
We should ask the screeners and administrators which questions are actually required.
We may also want to mark questions or present them in a context that implies who is asking and why.

**Comment by mapsam** [comment]
Totally. There's also this assumption that the entire set of patient's details _needs_ to be filled out in one-fell-swoop. I wonder how we can ensure people that it's not all or nothing.

**Comment by bengolder** [comment]
I think this will be a long-term issue, and we may want to think about a _process_ for dealing with it rather than trying to just answer which questions are required right now. There are a few points in the process where we could answer this need:
1. When adding new questions from a service, negotiating with services to designate which fields are required or optional.  
2. When displaying a field, indicate who is asking and why in some sort of help text or explanatory text.  
3. If questions become a model in our database, we could have a help page for each question, and possibly include a little Q & A about it there.  

I'm wondering if it would be possible to have services define their own questions, allow other services to ask about those questions, and generally have a Q & A process that can help a service understand which fields are unclear or problematic and either write documentation to help with those questions or edit their questions to be clearer. In other words, how can we help them reach clearer, easier eligibility questions?

**Comment by esmithayer** [comment]
There are sort of two different ideas of "required" here: required in order to save a new patient to the database, and required in order for the patient to submit a complete application for screening. Totally agree that the latter is a long-term issue, but the former is simpler. Right now you can add a patient with no name or DOB or any information at all, which probably doesn't make sense. Can we try adding some "required" styling/validation to (for example) the name and DOB fields and see if that helps users understand that they don't have to fill the whole thing out at once?

**Comment by bengolder** [comment]
@esmithayer Thanks, that's a good point. I'll add "not allowed to be blank" validation to my validation todos in #139.

**Comment by bengolder** [comment]
In terms of marking required fields, I've been looking for [more info](http://www.amazon.com/Web-Form-Design-Filling-Blanks/dp/1933820241) on form usability best practices, and a common recommendation is to generally not show fields that aren't required, but if we do show optional fields, mark them as optional. 

In terms of the form for adding a new patient, perhaps we should just show Name, DOB, and SSN, with SSN marked as optional, and exclude the rest of patient details. This could also tie into #138, and we could tie it to a search to see if the patient already exists or not. 

This way they could quickly save a new patient, there's less confusion about what is required, and they could optionally move on to a full screening form.
