### ISSUE TITLE
Replace user creation/login with something more robust

### ISSUE THREAD

**Issue by esmithayer** [codeforamerica/rva-screening#171]
With forgot password workflow, email validation, etc, and automatic logout after some period of time.

Persona?

**Comment by mapsam** [comment]
After some in-depth research, we have come the conclusion that Persona is actually not HIPAA compliant and will not work for our app. Persona is nice, but doesn't allow you to fully log a person out unless they manually go to persona.org and log yourself out of the app. This directly conflicts with the requirement to automatically log a user out after a period of inactivity.

@esmithayer has since built our own login/logout system that includes resetting of passwords using Flask-Security in #236. Therefore this is closed!
