### ISSUE TITLE
Prevent duplicate referrals

### ISSUE THREAD

**Issue by esmithayer** [codeforamerica/rva-screening#181]
Right now, the "share patient" page has nothing to indicate whether a patient has already been referred to a particular service, and clicking a button multiple times will create multiple referrals in the database.

We should probably prevent this, but there's some room for interpretation. Should we prevent the user from creating a referral:
- If this user has referred this patient to this service recently?
- If someone at this user's organization has referred this patient to this service recently?
- If anyone in the network has referred this patient to this service recently?
- If the patient has a current referral to this service in an open status?

**Comment by mapsam** [comment]
All good questions. I like the idea that a referral can't be made again until someone on the other end has marked it as "confirmed". I'm not sure how this interaction would work though.

What if we, for the sake of this week, say _when_ the last referral to that particular service was next to the share/notify button? This notice would show up for any user within the service that made the referral, rather than just for that specific user. 

For example: `user A` from `clinic 1` sends a referral to `clinic 2`. `User B` from `clinic 1` logs in later, and if they went to the same patient's profile to share it would say `user 1` shared with `clinic 2` last week. Furthermore, any user from `clinic 2` would log in and see the referral from `user A` at `clinic 1`. Once a user from `clinic 2` checks it as "confirmed", the referral action becomes available again for any user at `clinic 1`.

Cripes, does that make any sense?

**Comment by mapsam** [comment]
Currently the application says "view the open referral", instead of allowing for duplicates.
<img width="814" alt="screen shot 2015-11-17 at 9 24 32 am" src="https://cloud.githubusercontent.com/assets/1943001/11219053/0936a9f4-8d0d-11e5-9b5b-16c2d8891c42.png">
