### ISSUE TITLE
Make the mockups

### ISSUE THREAD

**Issue by mapsam** [codeforamerica/rva-screening#235]
Working branch: `make-the-mocks`

Components
- [x] patient sidebar navigation
- [x] notifications
- [x] patient header
- [x] filters on landing page

Views
- [x] **NEW** patient overview page
  - [x] created route
  - [x] edit history
  - [x] referral history
- [x] **NEW** referral > review & send
- [x] **UPDATE** landing page
- [x] **UPDATE** patient details > view/edit basic info
- [x] login/security page styles

**Comment by mapsam** [comment]
Patient sidebar navigation:

<img width="1154" alt="screen shot 2015-09-15 at 11 26 48 am" src="https://cloud.githubusercontent.com/assets/1943001/9885952/c2ed4508-5b9c-11e5-9bfd-90737db09b74.png">

Notifications:

<img width="1134" alt="screen shot 2015-09-15 at 11 26 53 am" src="https://cloud.githubusercontent.com/assets/1943001/9885958/c7d73204-5b9c-11e5-8d9a-3d06566f17bb.png">

**Comment by mapsam** [comment]
Patient header:

<img width="1137" alt="screen shot 2015-09-15 at 12 17 18 pm" src="https://cloud.githubusercontent.com/assets/1943001/9887316/d103e26c-5ba3-11e5-9ca3-86124af28337.png">

**Comment by mapsam** [comment]
Updated filters

![zipscreen-filters](https://cloud.githubusercontent.com/assets/1943001/9889082/98c24a2e-5bad-11e5-9c7a-e9288537dbfc.gif)

_note: colors are definitely not chosen here_ :wink:

**Comment by mapsam** [comment]
Started working on patient overview page and incorporated the patient header, navigation, and notifications:

<img width="990" alt="screen shot 2015-09-17 at 9 59 32 pm" src="https://cloud.githubusercontent.com/assets/1943001/9952215/83ca06a8-5d87-11e5-9f53-fd502ba4884f.png">

**Comment by mapsam** [comment]
@esmithayer starting to work on the filters on the landing page. I moved the new filter names from `views.py` into the `index.html` template and am getting a different error:

```
ProgrammingError: (ProgrammingError) missing FROM-clause entry for table "patient_referral"
LINE 6: ..._referral.status = 'COMPLETED') ORDER BY coalesce(patient_re...
```

[Here is the full error](https://gist.github.com/mapsam/5959213a72bdde9e352b)

**Comment by esmithayer** [comment]
Hmm do you have the full stack trace?

**Comment by mapsam** [comment]
Filter styles and counts have been added to the landing page:

<img width="1116" alt="screen shot 2015-09-21 at 5 07 07 pm" src="https://cloud.githubusercontent.com/assets/1943001/10008417/39e039aa-6083-11e5-8a47-02db009b0b74.png">

**Comment by mapsam** [comment]
@esmithayer I'm confused on a couple of these, would you mind clearing up some questions?
1. In regards to the "review & send page" are we still putting unique clinic questions there? If not, does the page stay the same as the make referral page then?
2. Do we want to have new information in the filter lists on the landing page? If so, what info?
3. The patient overview page exists, but I'm not exactly sure what information goes on it. General sums (i.e. FPL) and the form that allows a clinic to say if the individual is eligible or not?
4. Referral history page - stays the same?

Thanks!

**Comment by esmithayer** [comment]
1. [x] I think we decided not to put the unique clinic questions on there. We talked about changing the behavior when the user sends a referral, though--like listing who sent the referral and when rather than just saying "referral sent", and if the patient already has a screening result for a given organization, listing that rather than the prescreening results.
2. [x] When I showed this to people at Daily Planet, they were less interested in DOB and more interested in when the referral was from. It seems like it would make sense to list the completion date for completed referrals, the creation date for open referrals, and the renewal due date for patients who need updates (i.e. the date that's a year after their last document update). The to/from organization could be useful for the outgoing/incoming referral lists too.
3. [x] Yeah, I think household size, income, FPL%, documents, and the screening result form that's currently on the referral history page. Maybe also the "do you currently have insurance" and "how long have you lived in the area" questions since we know those are key to the determination at some orgs.
4. [x]  I think we had discussed some possible ways to reorganize it, but I don't remember deciding anything. We can remove the screening result form if we're putting that on the new patient overview page, but other than that probably makes sense to leave it for now unless there's something you're excited about changing.

**Comment by mapsam** [comment]
@esmithayer most of this is just about done. In order to get the first one complete, I'll need the proper models to reference in the templates (i.e. to show "has been actually approved for services at Daily Planet" vs. "likely eligible for services at Daily Planet") - what are the proper models to hit for that?

**Comment by esmithayer** [comment]
You'll want to look at patient.screening_results--you can filter for ones with a particular service id within Jinja using something like this:

```
{{ patient.screening_results | selectattr("service_id", service.id) }}
```

If that doesn't return results, the patient doesn't have any screening results for that service. If it does, you can look at the eligible_yn and sliding_scale attributes (like the referral/screening history page does right now).
