### ISSUE TITLE
What should be contained on a Client Summary Page?

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#3]
On the page where a screener can see an overview of a particular client, what information should be included?
- Name
- FPL
- Verification documents (with or without previews? list or summary?)
- Other services they might be eligible for?

![screen shot 2015-03-20 at 2 01 02 pm](https://cloud.githubusercontent.com/assets/451510/6760807/92d8dcd0-cf09-11e4-88c5-46665dc0583e.png)

**Comment by mapsam** [comment]
If we're having an overview page, it seems like actually listing the user information and documents would be helpful here, rather than making a user go to another screen. Turn the "see Cary's 2 documents" into "add another document" and "see Cary's details" should just be listed. Something like:

![screen shot 2015-03-20 at 2 21 38 pm](https://cloud.githubusercontent.com/assets/1943001/6761080/898203ca-cf0c-11e4-91bb-87d919ba7611.png)

working on [this template](https://docs.google.com/a/codeforamerica.org/presentation/d/1AOSlGJzVjRhTlpKJuXB5AVlUikPj5jplZrNZaTneles/edit#slide=id.g75bad4cc0_065) if you're needing copies

**Comment by bengolder** [comment]
I like that idea! It brings up a question about the list format for documents.

Here's a list of the info for each document that's being considered for inclusion in a document list page. Which should be included here?
- Document Name
- Document thumbnail image
- date of the document (like paystubs for the month of ___, or letter of child support about __ dates)
- date verified
- who reviewed it where
- whether and why it needs to be updated

Some of these were brought up by @esmithayer here:
https://docs.google.com/a/codeforamerica.org/presentation/d/1kVSFagS9laHCniL0LRNoi-thlp67J9w3oiGaUlbYAsQ/edit#slide=id.g75baf0228_043

**Comment by mapsam** [comment]
Good question! Of the list above, it seems **document name**, **date**, and **who reviewed** would be important to get quickly on this page. Could use icons like a :white_check_mark: or :exclamation: for the _needs to be updated_ portion as well.

**Comment by bengolder** [comment]
This is now being handled by the client details view, #36
