### ISSUE TITLE
How much info is needed to identify a client?

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#4]
Which should be used for a screener to find a client? If we create client-facing functionality, which should be used to allow a client to access their own account?
- Name
- Phone
- Date of birth
- Photo ID?

![screen shot 2015-03-20 at 2 04 00 pm](https://cloud.githubusercontent.com/assets/451510/6760873/6e306262-cf0a-11e4-87ef-5d99834cf368.png)

**Comment by mapsam** [comment]
I believe @esmithayer has mentioned **date of birth** being the typical identifier for patients in her work. What's the fallback from that?

**Comment by mapsam** [comment]
Interesting (kinda related) side note: There's a [good deal out there](http://library.ahima.org/xpedio/groups/public/documents/ahima/bok1_044000.hcsp?dDocName=bok1_044000) about matching records between systems, which seem to aim for demographic data since health record systems have their own unique identifiers that aren't shared between other systems. Sounds like an awful mess of demographic algorithm chaos.

**Comment by bengolder** [comment]
It seems like Name, DOB, phone number, and possible SSN should be sufficient. This is being addressed in the Patient ID portion of #36
