### ISSUE TITLE
include glyphicons in assets

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#47]
We should add the glyphicons fonts to the assets in `master` branch. Sub-issue of #42.

**Comment by mapsam** [comment]
@bengolder I can take care of this

**Comment by mapsam** [comment]
@bengolder I can take care of this one

**Comment by mapsam** [comment]
Hm, unfortunately Flask Assets or webassets have no recursive copy function unrelated to `Bundle`. That's a bummer. Currently I have a standard copy function using `shutil` and using the paths for `fonts`:

``` python
import shutil

def copyDirectory(src, dest):
    try:
        shutil.copytree(src, dest)
    # Directories are the same
    except shutil.Error as e:
        print('Directory not copied. Error: %s' % e)
    # Any error saying that the directory doesn't exist
    except OSError as e:
        print('Directory not copied. Error: %s' % e)

copyDirectory('app/static/node_modules/bootstrap/dist/fonts', 'app/static/public/fonts/')
```

@esmithayer I think this should be pushed into some sort of install script when Flask is set up for the first time, rather than running every time. Where would that go? We can probably remove the errors, since this function will only exist to copy over assets as needed. Or even further, we could probably just remove the need for defining a function and run:

``` python
shutil.copytree('app/static/node_modules/bootstrap/dist/fonts', 'app/static/public/fonts/')
```
