### ISSUE TITLE
Patient details expandable sections

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#58]

**Comment by mapsam** [comment]
Changing this one to be specific to expandable sections. Have added the checklist about the patient overview page to #36

**Comment by mapsam** [comment]
![rva-screener-expander](https://cloud.githubusercontent.com/assets/1943001/7596952/8302ac8a-f8a5-11e4-933a-6ac0df4f75ed.gif)

**Comment by mapsam** [comment]
During the quick demo I realized that these expander pieces kinda suck on desktop. Would it be useful to only have expanders work on mobile?

**Comment by bengolder** [comment]
@svmatthews yes

**Comment by mapsam** [comment]
yay!

**Comment by esmithayer** [comment]
So collapsible sections on desktop at all? They seem helpful to me, but if we're going to take them out we should probably rethink having only one save button at the bottom of the page.

**Comment by mapsam** [comment]
I thinks it's just the desktop interaction that seems off. It almost feels like we could tabulate the sections or something on desktop so you can at least see one at a time instead of having to deal with the screen moving up and down when all of the sections are collapsed. I'm not going to worry about this for next week, since it could be a rabbit hole. Will revisit after!

**Comment by bengolder** [comment]
After looking at it again, I agree with Emma that we should keep the collapsible sections on desktop for now.
![collapse](https://cloud.githubusercontent.com/assets/451510/7659806/96bf6762-faf9-11e4-82f8-bd201d1074a1.gif)
